---
- name: Setup Ubuntu VM with required software
  hosts: localhost
  become: true
  connection: local

  roles:
    - utilities
    - network-utils
    - awscli
    - rclone
    - docker
    - caddy
    - jq
    - tmux
    - zsh
    - gh
    - zerotier
    # Add more roles here as needed
    # - role_name
