---
- name: Setup Ubuntu with required software
  hosts: local
  become: true

  roles:
    - network-utils
    - ufw
    - utilities
    - awscli
    - rclone
    - ghcli
    - zerotier
    - fonts
    - docker
    - caddy
    - mongodb-tools
    - shell